### ISSUE TITLE
Chefkoch.de 400 Badrequest beim Video starten

### ISSUE THREAD

**Issue by finishlast** [AddonScriptorDE/plugin.video.chefkoch_de#1]
Im Chefkochplugin kann man die einzelnen  Videos sehen, aber sobald man eins startet kommt ein Scriptfehler, habe XBMC Eden probiert, da kommt kein Scriptfehler, es passiert gar nichts, auf XBMC 12 RC2 kommt wie gesagt ein Pythonfehler.

Im Log steht 400 Bad Request.

**Comment by AddonScriptorDE** [comment]
Hi,
die haben auf der Seite was geändert, nen Fix gibts hier: http://www.xbmcnerds.com/index.php?page=Thread&postID=89736#post89736
Ich pack die Version die Tage dann auch ins Repo...

**Comment by finishlast** [comment]
Super, danke, werd ich gleich mal updaten!

**Comment by AddonScriptorDE** [comment]
Gerne :) Sorry dass es so lang gedauert hat...
