### ISSUE TITLE
Error Contents: list index out of range

### ISSUE THREAD

**Issue by thtuerk** [AddonScriptorDE/plugin.video.chefkoch_de#3]
Zunächst möchte ich mich für das schöne Plugin bedanken. Leider hat es, als ich es ausprobierte, jedoch nicht funktioniert. Es scheint sich wieder etwas auf der Chefkoch.de Seite getan zu haben. Ich bekam eine `list index out of range` exception.

In Zeile 64 von `default.py` scheint es keine Treffer mehr zu geben

`match=re.compile("'http://www.chefkoch.de/video_streaming/video-playlist-xml.php\\?video_id=(.+?)'", re.DOTALL).findall(content)`

Wenn man den regulären Ausdruck zu `mediaid : (.+?),`, Zeile 64 also zu

`match=re.compile("mediaid : (.+?),", re.DOTALL).findall(content)`

ändert, scheint es wieder zu funktionieren.

**Comment by AddonScriptorDE** [comment]
Sorry für die späte Antwort. Hatte soviel zu tun und hab jetzt erst hier reingeschaut.
Ist mittlerweile gefixt.
